apiVersion: apps/v1
kind: Deployment
metadata:
  name: pygamebreaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pygamebreaker
  template:
    metadata:
      labels:
        app: pygamebreaker
    spec:
      containers:
      - name: pygamebreaker
        image: chinnuworkspace/pygamebreaker:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app.py"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
