apiVersion: apps/v1
kind: Deployment
metadata:
  name: pygamebreaker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pygamebreaker
  template:
    metadata:
      labels:
        app: pygamebreaker
    spec:
      containers:
      - name: pygamebreaker
        image: chinnuworkspace/pygamebreaker:latest
        ports:
        - containerPort: 5000
        env:
        - name: DISPLAY
          value: ":99"  # Change this to match the Dockerfile
        command: ["xvfb-run", "python3", "breaker_game.py", "$(pwd)", "PlayerName"]